Repository stolostron/multicloud-operators-subscription, pull requests merged in 2019-10, with the labels that each got.

#1 Adding owner
  OWNERS
Labels: approved, lgtm, size/XS

#2 initial check in with CRD only
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  OWNERS
  README.md
  RELEASE.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  deploy/crds/app_v1alpha1_subscription_cr.yaml
  deploy/crds/app_v1alpha1_subscription_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/development.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_app_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/app/group.go
  pkg/apis/app/v1alpha1/doc.go
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_subscription.go
  pkg/controller/controller.go
  pkg/controller/subscription/subscription_controller.go
  tools.go
  version/version.go
Labels: approved, lgtm, size/XXL

#3 add synchronizer and cleanup linting issues
  Dockerfile
  Makefile
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  cmd/manager/main.go
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/subscription_types_test.go
  pkg/apis/app/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/controller.go
  pkg/controller/subscription/subscription_controller_suite_test.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/synchronizer/discovery.go
  pkg/synchronizer/extension.go
  pkg/synchronizer/sync_suite_test.go
  pkg/synchronizer/sync_test.go
  pkg/synchronizer/synchronizer.go
  pkg/synchronizer/validator.go
  pkg/utils/eventlog.go
  pkg/utils/kubernetes.go
  pkg/utils/override.go
  pkg/utils/subscription.go
  pkg/utils/template.go
  pkg/utils/util_suite_test.go
  pkg/utils/util_test.go
Labels: approved, lgtm, size/XXL

#4 switch to prow
  .travis.yml
  Makefile
  README.md
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: approved, lgtm, size/L

#8 update codecov link
  Makefile
  README.md
Labels: approved, lgtm, size/XS

#11 use operator-sdk to buil
  Dockerfile
  Makefile
  README.md
  common/scripts/install-operator-sdk.sh
  deploy/crds/app_v1alpha1_channel_crd.yaml
  deploy/crds/app_v1alpha1_deployable_crd.yaml
  deploy/crds/app_v1alpha1_subscription_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  docs/getting_started.md
  examples/helmrepo-channel/allinone.yaml
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/utils/subscription.go
Labels: approved, size/L

#12 build image with operator-sdk
  Makefile
  README.md
  common/scripts/install-operator-sdk.sh
Labels: approved, size/S

#13 fix go lint
  pkg/subscriber/helmrepo/subscriber_item.go
Labels: approved, lgtm, size/XS

#14 example ready
  README.md
  deploy/operator.yaml
  examples/helmrepo-channel/allinone.yaml
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/synchronizer/kubernetes/discovery.go
Labels: approved, lgtm, size/L

#16 add hub controller
  README.md
  pkg/controller/add_mcm_hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_suite_test.go
  pkg/controller/mcmhub/mcmhub_controller_test.go
  pkg/subscriber/namespace/namespace_subscriber.go
Labels: approved, lgtm, size/L

#18 make local and pass dco for members
  .github/dco.yml
  Makefile
  README.md
  common/scripts/codecov.sh
  docs/getting_started.md
Labels: approved, lgtm, size/M

#15 Minor fix on lines 30 & 45
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#20 Add GitHub repo initial implementation
  examples/github-channel/allinone.yaml
  go.mod
  go.sum
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/add_github_subscriber.go
  pkg/subscriber/github/github_subscriber.go
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/XL

#22 add link to release repo and some ut
  README.md
  pkg/subscriber/objectbucket/objectbucket_subscriiber_test.go
Labels: approved, lgtm, size/S

#24 GitHub repo doc
  docs/gitrepo_subscription.md
  examples/github-channel/00-namespace.yaml
  examples/github-channel/01-channel.yaml
  examples/github-channel/02-subscription.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#25 update subscription-release
  examples/namespace-channel/01-channel.yaml
  examples/namespace-channel/02-subscription.yaml
  go.mod
  go.sum
  hack/test/app_v1alpha1_deployable_crd.yaml
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriiber_test.go
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/L

#26 add test for crd
  examples/namespace-channel/01-channel.yaml
  examples/namespace-channel/02-subscription.yaml
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_suite_test.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/L

#23 Importcycle
  common/config/.hadolint.yml
  go.mod
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/secret_reconciler.go
Labels: approved, lgtm, size/L

#29 Add filter and override
  pkg/subscriber/github/github_subscriber.go
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/L

#27 subscription hub update
  Makefile
  cmd/manager/exec/manager.go
  examples/namespace-channel/03-dev2-subscription.yaml
  go.mod
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/eventlog.go
Labels: approved, lgtm, size/XL

#30 use right namespace for default, seprate dpl,secret controllers
  cmd/manager/exec/manager.go
  pkg/subscriber/namespace/namespace_subscriber.go
Labels: approved, lgtm, size/M

#31 set placement local to true in subscription template
  pkg/controller/mcmhub/hub.go
Labels: approved, lgtm, size/XS
