Repository stolostron/multicloud-operators-subscription, pull requests merged in 2019-11, with the labels that each got.

#32 separate syncsuorce for different subscriber and controller/function inside subscriber
  cmd/manager/exec/manager.go
  cmd/manager/main.go
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/github/github_subscriber.go
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/hemrepo_subscriber.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/subscriber/objectbucket/objectbucket_subscriber.go
  pkg/subscriber/objectbucket/subscriber_item.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/M

#33 syncrhonizer wait a cycle before start
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/M

#34 .kubernetesIgnore feature
  docs/gitrepo_subscription.md
  examples/github-channel/sub1.yaml
  go.mod
  go.sum
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/L

#35 clusterscope subscription deploys template to its namespace
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriiber_test.go
Labels: approved, lgtm, size/M

#36 Add test files and apply kube resources in order
  common/Makefile.common.mk
  pkg/subscriber/github/subscriber_item.go
  test/github/helmcharts/chart1/Chart.yaml
  test/github/helmcharts/chart1/charts/subchart1/Chart.yaml
  test/github/helmcharts/chart1/charts/subchart1/templates/minio-secret.yaml
  test/github/helmcharts/chart1/templates/configmap.yaml
  test/github/helmcharts/chart1/values.yaml
  test/github/helmcharts/chart2/Chart.yaml
  test/github/helmcharts/chart2/charts/subchart1/Chart.yaml
  test/github/helmcharts/chart2/charts/subchart1/templates/minio-secret.yaml
  test/github/helmcharts/chart2/templates/configmap.yaml
  test/github/helmcharts/chart2/values.yaml
  test/github/resources/.kubernetesIgnore
  test/github/resources/configmap.yaml
  test/github/resources/deploy/crds/crontab.yaml
  test/github/resources/deploy/sub1_cm.yaml
  test/github/resources/deploy/sub1_invalid.yaml
  test/github/resources/deploy/sub1_secret.yaml
  test/github/resources/invalid.yaml
  test/github/resources/namespace.yml
  test/github/resources/rbac/clusterrole.yml
  test/github/resources/rbac/clusterrolebinding.yaml
  test/github/resources/rbac/sa.yaml
  test/github/resources/secret.yaml
Labels: approved, lgtm, size/L

#39 fix issues in using wrong local client and not return with error when…
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/XS

#38 Rename kubernetes ignore
  docs/gitrepo_subscription.md
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_suite_test.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_test.go
  pkg/subscriber/namespace/namespace_subscriber_suite_test.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_suite_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_test.go
  pkg/utils/subscription.go
Labels: approved, lgtm, size/M

#37 subscription Rolling update
  examples/namespace-channel/rollingupdate/rollingupdate-subscription.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/controller/mcmhub/hub.go
Labels: approved, lgtm, size/L

#28 Deploy Helmrepo referred secert and secret func refactor
  go.mod
  pkg/controller/subscription/reference.go
  pkg/controller/subscription/reference_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/secretkit.go
Labels: approved, lgtm, size/XL

#40 move to sdk012
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  cmd/manager/main.go
  common/scripts/install-operator-sdk.sh
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller_test.go
  pkg/controller/subscription/reference.go
  pkg/controller/subscription/reference_test.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_test.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_test.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/utils/util_test.go
  tools.go
Labels: approved, lgtm, size/XL

#41 Helm
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#42 replace masterminds semver version
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#43 Add tests
  deploy/standalone/app_v1alpha1_channel_crd.yaml
  go.mod
  go.sum
  hack/test/app_v1alpha1_channel_crd.yaml
  pkg/subscriber/github/github_subscriber.go
  pkg/subscriber/github/github_subscriber_suite_test.go
  pkg/subscriber/github/github_subscriber_test.go
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/L

#44 Timewindow
  .gitignore
  deploy/crds/app_v1alpha1_subscription_crd.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/subscriber/objectbucket/subscriber_item.go
  pkg/utils/timewindow.go
  pkg/utils/timewindow_test.go
  pkg/utils/version_test.go
Labels: approved, lgtm, size/XXL

#45 Codefix and tests
  pkg/subscriber/github/github_subscriber_test.go
  pkg/subscriber/github/subscriber_item.go
  test/github/helmcharts/otherCharts/chart1/Chart.yaml
  test/github/helmcharts/otherCharts/chart1/charts/subchart1/Chart.yaml
  test/github/helmcharts/otherCharts/chart1/charts/subchart1/templates/minio-secret.yaml
  test/github/helmcharts/otherCharts/chart1/templates/configmap.yaml
  test/github/helmcharts/otherCharts/chart1/values.yaml
Labels: approved, lgtm, size/L

#46 Update doc
  docs/gitrepo_subscription.md
Labels: approved, lgtm, size/XS

#47 pickup release change of uninstall release
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#48 Fixownerref4referredresouce
  pkg/controller/subscription/reference.go
  pkg/controller/subscription/reference_test.go
Labels: approved, lgtm, size/L

#49 Harvest exsting resource rather than del
  go.mod
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
Labels: approved, lgtm, size/XL

#50 Support GitHub branch
  examples/github-channel/sub1.yaml
  pkg/subscriber/github/github_subscriber_test.go
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/L

#51 Releasecheck
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#52 fixing issue 932
  go.mod
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/github/github_subscriber_test.go
  pkg/subscriber/objectbucket/subscriber_item.go
Labels: approved, lgtm, size/S

#54 add missing md suffix to getting_started link
  README.md
Labels: approved, lgtm, size/XS

#53 Keyword
  go.mod
  go.sum
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/utils/version.go
Labels: approved, lgtm, size/S

#55 Issue933
  go.mod
  go.sum
  pkg/controller/subscription/reference.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/namespace/secret_reconciler.go
Labels: approved, lgtm, size/L

#57 Issue187objectversion
  pkg/subscriber/objectbucket/subscriber_item.go
  pkg/utils/aws/objectstore.go
Labels: approved, lgtm, size/M

#56 Tolerate incomplete api discovery, rediscover on resource deletion, record event, don't harvest resource being deleted
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/L

#58 rolling update new fixes
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, lgtm, size/L

#59 Short
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  deploy/standalone/app.ibm.com_subscriptions_crd.yaml
  deploy/standalone/app_v1alpha1_subscription_crd.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/util_test.go
Labels: approved, lgtm, size/L

#60 Group
  go.mod
  go.sum
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/subscriber_item.go
Labels: approved, lgtm, size/S

#61 Relname
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#62 Referredresourceupdate
  pkg/controller/subscription/reference.go
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/secret_reconciler.go
Labels: approved, lgtm, size/M

#63 sync-source not hosting-subscription, pickup releasename change
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
  pkg/utils/util_test.go
Labels: approved, lgtm, size/M

#64 Readme
  README.md
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/M

#65 Annotation RollingUpdateMaxUnavailable need to be copied to subscription deployable
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/controller/mcmhub/hub.go
Labels: approved, lgtm, size/L

#66 Nopass
  go.mod
  go.sum
  pkg/controller/mcmhub/hub.go
Labels: approved, lgtm, size/M

#67 Gvk
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/S

#68 set hosting-subscription correctly
  pkg/synchronizer/kubernetes/extension.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/S

#69 update original subscription to its target subscription
  pkg/controller/mcmhub/hub.go
Labels: approved, lgtm, size/L

#70 new Standalone option
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  pkg/controller/add_mcm_hub.go
  pkg/controller/controller.go
Labels: approved, lgtm, size/M

#71 Add doc and example
  deploy/standalone/operator.yaml
  docs/gitrepo_subscription.md
  examples/github-channel/.kubernetesignore
  examples/github-channel/02-subscription.yaml
  examples/github-channel/10-namespace.yaml
  examples/github-channel/11-channel.yaml
  examples/github-channel/12-subscription.yaml
  examples/github-channel/sample-deployment.yaml
Labels: approved, lgtm, size/L

#72 Fixes
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_test.go
Labels: approved, lgtm, size/M

#73 Newobj
  deploy/standalone/operator.yaml
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/XS

#74 Fixnil
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/S
