Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-10, with the labels that each got.

#309 [WIP] Prehook display on failure
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/metaupdate.go
Labels: approved, do-not-merge/work-in-progress

#310 Create git webhook listener service
  cmd/manager/exec/manager.go
  pkg/webhook/listener/bitbucket_events_test.go
  pkg/webhook/listener/gitlab_events_test.go
  pkg/webhook/listener/webhook_listener_test.go
  pkg/webhook/listener/webhook_listner.go
  pkg/webhook/webhook.go
Labels: approved, lgtm

#312 Update synchronizer.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#311 fix managed cluster status update
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/synchronizer/kubernetes/extension.go
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/utils/deployable.go
  pkg/utils/subscription.go
  pkg/utils/subscription_test.go
Labels: approved, lgtm

#314 Fix private Git secret
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/utils/gitrepo.go
Labels: approved

#315 Fix git helm subscription
  pkg/utils/helmrepo.go
Labels: approved

#313 fix the git watcher
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_git.go
  pkg/controller/mcmhub/hook_git_test.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, lgtm

#317 correct dayofWeek Time window valiadation
  pkg/utils/timewindow.go
Labels: approved

#316 [WIP] adding info log
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_git.go
  pkg/controller/mcmhub/hub_git_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, do-not-merge/work-in-progress

#320 do not process on helm subscription if the server is in a unhealthy state
  deploy/standalone/apps.open-cluster-management.io_channel_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_channels_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_deployable_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_deployables_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_helmreleases_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_subscriptions.yaml
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: approved, lgtm

#322 fix a bug where deregistering helmrelease is happening unintentionally
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: approved, lgtm

#321 prehook status applied upon pending or fail
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_git.go
  pkg/controller/mcmhub/hub_git_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved

#323 Update webhook_listner.go
  pkg/webhook/listener/webhook_listner.go
Labels: approved, lgtm

#325 Update synchronizer.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#324 use safer status update method
  Makefile
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub_git.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/gitrepo.go
Labels: approved

#326 adding logic to cover edge case
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub_git.go
Labels: approved

#327 skip creating ansiblejob that are coming from a forceregister when there are no other ansiblejob on the record
  pkg/controller/mcmhub/ansiblejob.go
Labels: lgtm

#328 Fix deep equal of annotation
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/subscription.go
  pkg/utils/subscription_test.go
Labels: approved, lgtm

#329 skip the target_clusters dupe ansible job check if commitID has been changed
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, lgtm

#330 Fix customize override in multiple subscriptions using the same channel
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub_git.go
Labels: approved

#331 Fix multi-doc YAML parsing
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
  pkg/utils/kustomize_test.go
  test/github/multiresource/multiresource.yaml
Labels: approved

#332 Fix multi-document YAML parsing
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
  test/github/multiresource/multiresource.yaml
Labels: approved

#333 avoid index out of range panic when removing base dir prefix
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
Labels: approved
