Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-06, with the labels that each got.

#205 skip CheckAndInstallCRD() test
  pkg/utils/util_test.go
Labels: approved, lgtm

#206 Support custom namespace for git subscription
  go.mod
  go.sum
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
Labels: approved

#207 Subscription admin rbac update
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/utils/gitrepo_test.go
Labels: approved

#210 Append hosting subscription annotations when a new namespace is created
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#212 upgrade channel version
  go.mod
  go.sum
Labels: lgtm

#208 Izhang helm anno
  .travis.yml
  examples/e2e_example/namepsace_channel_e2e.yaml
  examples/e2e_example/object_bucket_channel_e2e.yaml
  go.mod
  go.sum
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_test.go
  pkg/controller/mcmhub/metaupdate.go
  pkg/controller/mcmhub/metaupdate_test.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/utils/helmrepo.go
Labels: approved, lgtm

#215 Update gitrepo.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
Labels: approved

#214 Izhang git helm update v2
  examples/e2e_example/github_helm_channel_e2e.yaml
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_test.go
  pkg/controller/mcmhub/metaupdate.go
  pkg/controller/mcmhub/metaupdate_test.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: approved, lgtm

#216 Fix deleted resources
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/synchronizer/kubernetes/extension.go
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
Labels: approved, lgtm

#218 Bitbucket test
  pkg/subscriber/git/git_subscriber_test.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
Labels: approved

#219 Izhang fix reference namespace
  pkg/controller/subscription/subscription_controller.go
Labels: approved

#220 Continuously reconcile differences in cluster resources with repo
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#217 Izhang k8sclient datarace
  examples/e2e_example/github_channel_e2e.yaml
  examples/e2e_example/github_helm_channel_e2e.yaml
  go.sum
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/synchronizer/kubernetes/sync_test.go
Labels: approved, lgtm

#221 Fix git subscription reconcile
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/subscription.go
Labels: approved, lgtm

#222 Update go.sum
  go.sum
Labels: approved, lgtm

#223 Izhang reformat topo annotation
  pkg/controller/mcmhub/metaupdate.go
  pkg/controller/mcmhub/metaupdate_test.go
Labels: approved, lgtm

#224 Update UBI image
  build/Dockerfile
Labels: approved, lgtm

#225 Record sub admin role elevation events
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/subscription/subscription_controller.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
Labels: approved, lgtm

#226 Reduce subscription admin permissions
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, lgtm

#227 ensure helmrelease URLs are valid
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
Labels: approved, lgtm

#228 Fix subscription status
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/gitrepo.go
Labels: approved, lgtm
