Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-07, with the labels that each got.

#229 Pause subscription on managed cluster
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
Labels: approved, lgtm

#230 Improve subscription status
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, lgtm

#233 use the new helmrelease version
  go.mod
  go.sum
Labels: approved, lgtm

#234 don't update subscription if there is no change in git subscription a…
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub.go
Labels: approved

#236 cluster role and binding name changes
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/gitrepo.go
Labels: approved

#237 compare subscription annotation not working due to the same sub obj i…
  pkg/controller/mcmhub/gitrepo_sync.go
Labels: approved, lgtm

#238 shut down the eventBroadcaster explictly to avoid goroutine leakage
  pkg/controller/mcmhub/metaupdate.go
Labels: approved, lgtm

#240 Fix status update loop
  pkg/utils/deployable.go
Labels: approved

#243 After a local subscription is paused, its deployed resources are removed
  pkg/controller/subscription/subscription_controller.go
Labels: approved

#242 adding test case
  cmd/manager/exec/manager.go
  pkg/utils/deployable.go
  pkg/utils/deployable_test.go
Labels: approved

#245 Fix namespace subscription reconcile status update
  pkg/controller/subscription/subscription_controller.go
  pkg/utils/deployable.go
Labels: approved, lgtm

#246 recreate the helmrelease cr if it's deleted
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: approved

#249 existing service resource update failed due to serviceGVR being defin…
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#250 deployed subscription failed to write status back to hub deployable
  pkg/utils/deployable.go
Labels: approved, lgtm

#255 deleted resources are re-created by the paused subscription
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
Labels: approved, lgtm

#257 update subscription-release version
  go.mod
  go.sum
Labels: lgtm

#248 implement the compare and submit approach of status field
  pkg/subscriber/processdeployable/deployable_queue.go
  pkg/utils/subscription.go
  pkg/utils/subscription_test.go
Labels: approved

#258 update subscription release version
  go.mod
  go.sum
Labels: approved, lgtm

#259 Object bucket topo
  examples/e2e_example/object_bucket_channel_e2e.yaml
  go.mod
  go.sum
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved
