Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-04, with the labels that each got.

#150 make crds compatible with kube 1.1, 1.3
  deploy/crds/apps.open-cluster-management.io_subscriptions_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_helmrelease_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_subscriptions_crd.yaml
  go.mod
  go.sum
  hack/test/apps.open-cluster-management.io_helmrelease_crd.yaml
Labels: lgtm

#153 Update .travis.yml
  .travis.yml
Labels: lgtm

#159 Install Git in docker image
  build/Dockerfile
Labels: lgtm

#160 use the new helm releaes which has remediate security scan
  go.mod
  go.sum
Labels: lgtm

#162 fixed potential panic crash
  pkg/subscriber/helmrepo/subscriber_item.go
Labels: lgtm

#168 Izhang reduce secret reconciles
  examples/e2e_example/namepsace_channel_e2e.yaml
  examples/e2e_example/object_bucket_channel_e2e.yaml
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/secret_reconciler.go
Labels: approved, lgtm

#169 undo skip update helmrelease check
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
Labels: approved, lgtm

#171 update new helmrelease version
  go.mod
  go.sum
Labels: lgtm

#172 More tests 420
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
Labels: approved

#174 new cmd uninstall-crd
  Makefile
  build/Dockerfile
  cmd/uninstall-crd/uninstall-crd.go
Labels: approved, lgtm

#176 Izhang issue 170 v1
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#177 Fix subscription retry
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/controller/mcmhub/hub_test.go
  pkg/subscriber/github/github_subscriber.go
  pkg/subscriber/github/subscriber_item.go
Labels: approved

#178 added tests for uninstall-crd
  cmd/uninstall-crd/uninstall-crd.go
  pkg/utils/deployable.go
  pkg/utils/deployable_test.go
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
  pkg/utils/subscription.go
  pkg/utils/subscription_test.go
Labels: approved

#181 fix readme and improve test coverage
  README.md
  pkg/utils/deployable_test.go
  pkg/utils/helmrepo_test.go
  pkg/utils/subscription_test.go
Labels: approved, lgtm
