Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-09, with the labels that each got.

#277 Find secret from local subscription's NS, then channel's NS on hub
  pkg/subscriber/github/subscriber_item.go
Labels: lgtm

#279 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm

#280 Fix sonar scanned vulnerabilities
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/utils/cert.go
Labels: approved

#281 [WIP] Fix nested kustomize
  .travis.yml
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
  test/github/nestedKustomize/wordpress/kustomization.yaml
  test/github/nestedKustomize/wordpress/mysql/deployment.yaml
  test/github/nestedKustomize/wordpress/mysql/kustomization.yaml
  test/github/nestedKustomize/wordpress/mysql/secret.yaml
  test/github/nestedKustomize/wordpress/mysql/service.yaml
  test/github/nestedKustomize/wordpress/patch.yaml
  test/github/nestedKustomize/wordpress/wordpress/deployment.yaml
  test/github/nestedKustomize/wordpress/wordpress/kustomization.yaml
  test/github/nestedKustomize/wordpress/wordpress/service.yaml
  test/github/nestedKustomize/wordpress2/kustomization.yaml
  test/github/nestedKustomize/wordpress2/mysql/deployment.yaml
  test/github/nestedKustomize/wordpress2/mysql/kustomization.yaml
  test/github/nestedKustomize/wordpress2/mysql/secret.yaml
  test/github/nestedKustomize/wordpress2/mysql/service.yaml
  test/github/nestedKustomize/wordpress2/patch.yaml
  test/github/nestedKustomize/wordpress2/wordpress/deployment.yaml
  test/github/nestedKustomize/wordpress2/wordpress/kustomization.yaml
  test/github/nestedKustomize/wordpress2/wordpress/service.yaml
Labels: approved

#282 Update kustomize.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/utils/kustomize.go
Labels: approved

#283 watch placement rules on hub
  hack/test/apps.open-cluster-management.io_placementrules_crd.yaml
  pkg/apis/apis.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/subscription.go
Labels: approved

#275 [WIP] Ansible integeration
  Makefile
  build/run-code-lint.sh
  cmd/manager/exec/manager.go
  common/config/.golangci.yml
  deploy/crds/apps.open-cluster-management.io_subscriptions.yaml
  deploy/crds/apps.open-cluster-management.io_subscriptions_crd.yaml
  go.mod
  go.sum
  hack/test/tower.ansible.com_ansiblejobs_crd.yaml
  pkg/apis/apps/v1/register.go
  pkg/apis/apps/v1/subscription_types.go
  pkg/apis/apps/v1/zz_generated.deepcopy.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_git.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_suite_test.go
  pkg/controller/mcmhub/metaupdate.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/utils/gitrepo.go
  pkg/utils/subscription.go
  test/hooks/ansible/cfg_and_ansible.yaml
  test/hooks/ansible/posthook/sub_posthook.yaml
  test/hooks/ansible/prehook/sub_prehook.yaml
Labels: lgtm

#285 update ansiblejob spec.extra_vars.target_clusters with placementrule decision changes
  go.mod
  go.sum
  hack/test/clusters.open-cluster-management.io_managedclusters.crd.yaml
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/mcmhub_controller_suite_test.go
Labels: approved

#288 Ansible follow up
  common/config/.golangci.yml
  examples/e2e_example/local_deployalbe_e2e.yaml
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_git.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/gitrepo.go
  pkg/utils/subscription.go
Labels: approved, lgtm

#289 sfix invalid git repo
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/metaupdate.go
Labels: approved

#287 Subscriptions for managed hub cluster
  cmd/manager/exec/manager.go
  cmd/uninstall-crd/uninstall-crd.go
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/controller.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/subscription/reference_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/utils/subscription.go
Labels: approved

#291 Dev ansible status update
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/metaupdate.go
  pkg/utils/gitrepo.go
  pkg/utils/subscription.go
Labels: approved

#293 Subscription replace should annotate the objects like a normal subscription.
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm

#294 remove unused func and test
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_test.go
Labels: approved

#295 Fix timewindow tests
  pkg/controller/subscription/subscription_controller_suite_test.go
  pkg/controller/subscription/subscription_controller_test.go
Labels: approved, lgtm

#292 force register if the reconcile came from a placementrule update
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved

#296 adding the local == false flag
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/subscription.go
Labels: approved

#298 Update subscription_types.go
  pkg/apis/apps/v1/subscription_types.go
Labels: approved

#299 get rid of the late update
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved

#300 [WIP] make sure per reconcile, only 1 modification is made to k8s
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_suite_test.go
  pkg/utils/subscription.go
  pkg/utils/update_crds.go
Labels: approved, do-not-merge/work-in-progress

#302 fix a nil pointer if spec.Placement is nil
  pkg/controller/mcmhub/hook.go
Labels: approved, lgtm

#303 Fix kustomize hook path
  pkg/controller/mcmhub/hook_git.go
Labels: approved, lgtm

#301 convert placementrule CRD apiversion to v1beta1 for supporting <4.5 v…
  deploy/crds/apps.open-cluster-management.io_subscriptions.yaml
  pkg/apis/apps/v1/subscription_types.go
Labels: approved

#305 Fix blocked time window
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/utils/timewindow.go
  pkg/utils/timewindow_test.go
Labels: approved, lgtm

#304 make sure the applied jobs is updated to topo annotation
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hook_test.go
Labels: approved, lgtm

#306 [WIP] adding gitwatch on hub for hooks
  go.mod
  go.sum
  pkg/controller/mcmhub/hook.go
  pkg/controller/mcmhub/hook_git.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/gitrepo.go
  pkg/webhook/listener/github_events.go
Labels: approved, do-not-merge/work-in-progress

#307 Update hook test samples
  test/hooks/ansible/post-only/cfg_and_ansible.yaml
  test/hooks/ansible/post-only/posthook/sub_posthook.yaml
  test/hooks/ansible/pre-and-post/cfg_and_ansible.yaml
  test/hooks/ansible/pre-and-post/posthook/sub_posthook.yaml
  test/hooks/ansible/pre-and-post/prehook/sub_prehook.yaml
Labels: approved, lgtm

#308 Update subscription_controller.go
  pkg/controller/subscription/subscription_controller.go
  pkg/utils/gitrepo.go
Labels: approved, lgtm
