Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-01, with the labels that each got.

#78 Operatorhub
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/channels.app.ibm.com.crd.yaml
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/deployables.app.ibm.com.crd.yaml
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/helmreleases.app.ibm.com.crd.yaml
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/multicloud-operators-subscription.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/subscriptions.app.ibm.com.crd.yaml
  deploy/olm-catalog/multicloud-operators-subscription/multicloud-operators-subscription.package.yaml
Labels: approved, lgtm, size/XXL

#77 Versioncontrol
  go.mod
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: approved, lgtm, size/L

#79 Versioncontrol
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/utils/version.go
Labels: approved, lgtm, size/S

#80 Versioncontrol
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: approved, lgtm, size/M

#81 GitHub webhook
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  go.mod
  go.sum
  pkg/controller/subscription/subscription_controller.go
  pkg/webhook/add_webhook_listener.go
  pkg/webhook/listener/github_events.go
  pkg/webhook/listener/webhook_listener_suite_test.go
  pkg/webhook/listener/webhook_listener_test.go
  pkg/webhook/listener/webhook_listner.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#85 Support both polling repos for changes and webhook events
  cmd/manager/exec/manager.go
  deploy/operator.yaml
  deploy/service.yaml
  deploy/standalone/operator.yaml
  deploy/standalone/service.yaml
  pkg/subscriber/github/github_subscriber.go
  pkg/subscriber/github/subscriber_item.go
  pkg/webhook/listener/github_events.go
  pkg/webhook/listener/webhook_listener_test.go
Labels: approved, lgtm, size/L

#88 Fix webhook handling in hub
  docs/gitrepo_subscription.md
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/github/github_subscriber.go
  pkg/webhook/listener/github_events.go
  pkg/webhook/listener/webhook_listener_test.go
  pkg/webhook/listener/webhook_listner.go
Labels: approved, lgtm, size/M

#89 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#87 fix cinnabar 78
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/timewindow.go
  pkg/utils/timewindow_test.go
Labels: approved, lgtm, size/M

#86 Newcsv
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/multicloud-operators-subscription.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#90 GitHub wehbook route
  deploy/operator.yaml
  deploy/service.yaml
  deploy/standalone/operator.yaml
  deploy/standalone/service.yaml
  docs/gitrepo_subscription.md
Labels: approved, lgtm, size/M

#91 adding test case to reflect UI design
  pkg/utils/timewindow_test.go
Labels: approved, lgtm, size/XS

#92 remove setting of the helmrelease spec.releasename and change helmreleasecr name to use sub uid
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/helmreleases.app.ibm.com.crd.yaml
  deploy/olm-catalog/multicloud-operators-subscription/0.1.0/multicloud-operators-subscription.v0.1.0.clusterserviceversion.yaml
  deploy/standalone/app_v1alpha1_helmrelease_crd.yaml
  go.mod
  go.sum
  hack/test/app_v1alpha1_helmrelease_crd.yaml
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/subscriber_item.go
  pkg/utils/subscription.go
Labels: approved, lgtm, size/L

#93 Addingtimewindowtestcase
  pkg/utils/timewindow_test.go
Labels: approved, lgtm, size/M
