Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-08, with the labels that each got.

#260 add to watch channel changes
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/utils/subscription.go
Labels: approved, lgtm

#261 Use kustomize CLI to fix some issues
  build/Dockerfile
  go.mod
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/utils/gitrepo.go
Labels: approved

#262 Remove kustomize CLI and use module again
  build/Dockerfile
  go.mod
  go.sum
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/utils/gitrepo.go
  pkg/utils/kustomize.go
Labels: approved

#263 update sub-release version
  go.mod
  go.sum
Labels: lgtm

#253 Fix concurrent map access error
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/synchronizer/kubernetes/validator.go
Labels: lgtm

#267 Upgrade to golang 1.15 and pick up latest OCM modules
  .travis.yml
  go.mod
  go.sum
Labels: approved, lgtm

#268 Add inline patch kustomize test
  go.sum
  pkg/utils/gitrepo_test.go
  pkg/utils/kustomize_test.go
  test/github/kustomize/overlays/inlinePatch/kustomization.yaml
Labels: approved

#269 update subsription release version
  go.mod
  go.sum
Labels: approved, lgtm

#270 adding back the object bucket smaple
  examples/e2e_example/object_bucket_e2e.yaml
Labels: approved, lgtm

#274 [WIP] Resource overwrite by Git or ObjectBucket subscriptions
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
Labels: approved, do-not-merge/work-in-progress

#276 Fix helmchart deployable name to fix upgrade problem
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
  test/github/helmcharts/chart1Upgrade/Chart.yaml
  test/github/helmcharts/chart1Upgrade/charts/subchart1/Chart.yaml
  test/github/helmcharts/chart1Upgrade/charts/subchart1/templates/minio-secret.yaml
  test/github/helmcharts/chart1Upgrade/templates/configmap.yaml
  test/github/helmcharts/chart1Upgrade/values.yaml
Labels: approved, lgtm
