Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-02, with the labels that each got.

#94 Check pkg name
  pkg/controller/mcmhub/hub.go
Labels: approved, lgtm, size/S

#95 add optional packageAlias to spec
  README.md
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/subscriber_item.go
Labels: approved, lgtm, size/M

#97 Secretenhancement
  go.mod
  go.sum
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/synchronizer/kubernetes/validator.go
  pkg/utils/secretkit.go
  pkg/utils/subscription.go
Labels: approved, lgtm, size/L

#98 Fix git clone
  pkg/subscriber/github/subscriber_item.go
Labels: approved, lgtm, size/S

#99 Support timewindow status
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  examples/e2e_example/github_channel_e2e.yaml
  examples/e2e_example/helm_channel_e2e.yaml
  examples/e2e_example/namepsace_channel_e2e.yaml
  examples/e2e_example/object_bucket_channel_e2e.yaml
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_suite_test.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/utils/timewindow.go
  pkg/utils/timewindow_test.go
  pkg/utils/util_suite_test.go
Labels: approved, lgtm, size/XXL

#100 adjust the subscription type to make sure the operator-sdk v0.12.0 co…
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
Labels: size/L

#101 Refactor namespace subscriber
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/namespace_subscriber_test.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/subscriber/namespace/secret_reconciler_test.go
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, lgtm, size/XL

#102 use the new helmrelease api
  README.md
  deploy/crds/app.ibm.com_subscriptions_crd.yaml
  deploy/standalone/app_v1alpha1_helmrelease_crd.yaml
  docs/gitrepo_subscription.md
  examples/e2e_example/github_channel_e2e.yaml
  examples/github-channel/02-subscription.yaml
  examples/helmrepo-channel/02-subscription.yaml
  examples/namespace-channel/rollingupdate/rollingupdate-subscription.yaml
  go.mod
  go.sum
  hack/test/app_v1alpha1_helmrelease_crd.yaml
  pkg/apis/app/v1alpha1/subscription_types.go
  pkg/subscriber/github/subscriber_item.go
  pkg/subscriber/helmrepo/subscriber_item.go
Labels: approved, lgtm, size/L
