Repository stolostron/multicloud-operators-subscription, pull requests merged in 2020-05, with the labels that each got.

#188 Support other git servers
  deploy/standalone/clusterrole_binding.yaml
  deploy/standalone/namespace.yaml
  deploy/standalone/operator.yaml
  deploy/standalone/service.yaml
  deploy/standalone/service_account.yaml
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/utils/cert.go
  pkg/utils/cert_test.go
  pkg/webhook/listener/bitbucket_events.go
  pkg/webhook/listener/bitbucket_events_test.go
  pkg/webhook/listener/github_events.go
  pkg/webhook/listener/gitlab_events.go
  pkg/webhook/listener/gitlab_events_test.go
  pkg/webhook/listener/webhook_listener_test.go
  pkg/webhook/listener/webhook_listner.go
Labels: approved

#189 Add Git channel type
  deploy/standalone/apps.open-cluster-management.io_channel_crd.yaml
  deploy/standalone/apps.open-cluster-management.io_helmrelease_crd.yaml
  docs/gitrepo_subscription.md
  examples/e2e_example/github_channel_e2e.yaml
  examples/github-channel/01-channel.yaml
  examples/github-channel/02-subscription.yaml
  examples/github-channel/11-channel.yaml
  examples/github-channel/12-subscription.yaml
  go.mod
  go.sum
  hack/test/apps.open-cluster-management.io_channel_crd.yaml
  hack/test/apps.open-cluster-management.io_helmrelease_crd.yaml
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/add_git_subscriber.go
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_suite_test.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
  pkg/webhook/listener/github_events.go
  pkg/webhook/listener/webhook_listener_test.go
Labels: approved, lgtm

#190 Ignore gosec G601
  pkg/utils/override.go
  pkg/utils/subscription.go
Labels: approved

#193 Sync all managed cluster statuses to the parent subscription
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_test.go
Labels: approved, lgtm

#194 Fix issue 2212
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/github/subscriber_item.go
  pkg/synchronizer/kubernetes/discovery.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/gitrepo.go
Labels: approved

#195 fix gosec issues
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/gitrepo.go
Labels: approved, lgtm

#192 Option to disable webhook handler TLS
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  pkg/webhook/listener/webhook_listner.go
  pkg/webhook/webhook.go
Labels: approved, lgtm

#196 upgrade operator sdk
  go.mod
  go.sum
  pkg/subscriber/namespace/namespace_subscriber_suite_test.go
  pkg/synchronizer/kubernetes/sync_suite_test.go
Labels: lgtm

#197 fix up dependency
  go.mod
  go.sum
Labels: approved, lgtm

#198 Izhang perf test improve
  go.sum
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/synchronizer/kubernetes/sync_client.go
  pkg/synchronizer/kubernetes/sync_server.go
Labels: approved

#199 1. introduce Propagation Failed status; 2. rewrite error if channel i…
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
Labels: approved, lgtm

#201 Update git_subscriber_item.go
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, lgtm

#200 Update component version to 2.0
  COMPONENT_VERSION
Labels: approved, lgtm

#202 fix the retry logic of helmrepo subscriber
  .travis.yml
  examples/e2e_example/namepsace_channel_e2e.yaml
  examples/e2e_example/object_bucket_channel_e2e.yaml
  go.mod
  go.sum
  pkg/subscriber/git/git_subscriber_suite_test.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_suite_test.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/subscriber/processdeployable/deployable_queue.go
  pkg/synchronizer/kubernetes/sync_server.go
Labels: approved
