Repository stolostron/multicloud-operators-subscription, pull requests merged in 2021-06, with the labels that each got.

#503 fix manual sync
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/subscriber/helmrepo/hemrepo_subscriber.go
Labels: approved, dco-signoff: yes, lgtm

#502 revert to apply cached client; update appsub status if object bucket …
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/synchronizer/kubernetes/sync_server.go
Labels: approved, dco-signoff: yes, lgtm

#505 enable proxy for git clone
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: no

#506 for community hub deploy we don't need the application pod
  deploy/hub/application-operator.yaml
Labels: approved, dco-signoff: yes, lgtm

#510 Handle multiple Git SSH URL formats
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: no

#512 add helmrepo fail status
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/metaupdate.go
Labels: approved, dco-signoff: yes, lgtm

#514 Pass user and group from parent to child subscriptions
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes, lgtm

#516 handle when managed cluster does not support lease kind
  cmd/manager/exec/manager.go
  pkg/controller/subscription/lease_controller.go
  pkg/synchronizer/kubernetes/sync_test.go
Labels: approved, dco-signoff: yes, lgtm

#515 Add userid managed appsubs
  pkg/controller/mcmhub/hub.go
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes, lgtm

#518 Ansible jobs manual sync
  pkg/controller/mcmhub/ansiblejob.go
  pkg/controller/mcmhub/hook.go
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: no, lgtm

#519 Scan SSH hostname with the port
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: no, lgtm

#511 do not default to amd64 if GOARCH is not set
  common/scripts/gobuild.sh
Labels: approved, dco-signoff: yes, lgtm

#521 Handle case where there are no annotations before adding user
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes, lgtm

#520 Fix active time window in day of week earlier than current time
  pkg/utils/timewindow.go
  pkg/utils/timewindow_test.go
Labels: approved, dco-signoff: yes, lgtm

#523 handle destructive Git commits
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes, lgtm

#524 support AWS S3 bucket pagination for listing over 1000 objects
  pkg/utils/aws/objectstore.go
Labels: approved, dco-signoff: yes, lgtm

#526 do not remove app resources when subscription fails
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes
