Repository stolostron/multicloud-operators-subscription, pull requests merged in 2021-07, with the labels that each got.

#527 [WIP] update host subscription deployable status when fails
  Makefile
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/synchronizer/kubernetes/sync_client.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, dco-signoff: yes, do-not-merge/work-in-progress

#528 fix deployable update
  pkg/controller/mcmhub/gitrepo_sync.go
Labels: approved, dco-signoff: yes, lgtm

#530 trigger build to fetch latest ubi image
  README.md
Labels: approved, dco-signoff: yes, lgtm

#531 pick up new helmrelease controller
  go.mod
  go.sum
Labels: approved, dco-signoff: yes

#532 update version
  COMPONENT_VERSION
Labels: approved, dco-signoff: yes, lgtm

#534 no op, trigger cicd
  README.md
Labels: approved, dco-signoff: yes, lgtm

#535 update version to follow semantic versioning format
  COMPONENT_VERSION
Labels: approved, dco-signoff: yes, lgtm

#536 fix release-2.3 version
  COMPONENT_VERSION
Labels: approved, dco-signoff: yes, lgtm
