Repository stolostron/multicloud-operators-subscription, pull requests merged in 2021-04, with the labels that each got.

#467 Edit e2e tests
  examples/e2e_example/git-commit-subscription-e2e.yaml
  examples/e2e_example/git-tag-subscription-e2e.yaml
Labels: approved

#468 edit tests
  examples/e2e_example/git-commit-subscription-e2e.yaml
  examples/e2e_example/git-tag-subscription-e2e.yaml
Labels: approved

#471 Update e2e tests
  examples/e2e_example/git-commit-subscription-e2e.yaml
  examples/e2e_example/git-tag-subscription-e2e.yaml
Labels: approved, dco-signoff: no

#470 Upgrade kustomize
  .github/workflows/kind.yml
  build/run-e2e-tests.sh
  e2e/e2e_test.go
  go.mod
  go.sum
  pkg/utils/kustomize.go
Labels: approved, dco-signoff: no

#472 add a new subscription annotation
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/hub.go
Labels: approved, dco-signoff: yes

#474 Upgrade kustomize module
  go.mod
  go.sum
  pkg/utils/gitrepo_test.go
  pkg/utils/kustomize.go
  pkg/utils/kustomize_test.go
  test/github/kustomize/base/oauth-policy.yaml
  test/github/kustomize/overlays/patchjson2/cluster01-patch.yaml
  test/github/kustomize/overlays/patchjson2/kustomization.yaml
Labels: approved, dco-signoff: no

#475 update prow docker base image
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes, lgtm

#476 Fix Git ca certs
  pkg/controller/mcmhub/hub_git.go
Labels: approved, dco-signoff: yes

#477 create and update lease on managed cluster instead of hub cluster
  cmd/manager/exec/manager.go
  pkg/controller/mcmhub/hub_git.go
  pkg/controller/subscription/lease_controller.go
  pkg/controller/subscription/lease_controller_test.go
Labels: approved, dco-signoff: yes

#478 add release main branch
  RELEASE_MAIN_BRANCH
Labels: approved, dco-signoff: yes, lgtm

#479 Generate new image to fix CVE
  README.md
Labels: approved, dco-signoff: yes, lgtm

#481 go 16 and go mod tidy
  build/Dockerfile.prow
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm

#483 Fix go 16
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes, lgtm

#480 AWS S3 object store support
  go.mod
  go.sum
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/objectbucket/objectbucket_subscriber.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_test.go
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/utils/aws/objectstore.go
  pkg/utils/aws/objectstore_test.go
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes, lgtm

#484 Add example for nested subscription
  examples/e2e_example/git-nested-subscription-e2e.yaml
Labels: approved, dco-signoff: yes, lgtm

#485 remove codecov
  Makefile
  common/scripts/codecov.sh
Labels: approved, dco-signoff: yes, lgtm
