Repository stolostron/multicloud-operators-subscription, pull requests merged in 2021-09, with the labels that each got.

#564 fix secondary channel
  pkg/apis/apps/v1/zz_generated.deepcopy.go
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: yes

#566 convert invalid deployable name
  pkg/controller/mcmhub/gitrepo_sync.go
Labels: lgtm, approved, dco-signoff: yes

#568 fix proxy config
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: yes

#567 fix proxy config
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: yes

#569 update patch doc
  docs/patching_subscription_image.md
Labels: dco-signoff: yes

#570 fix synchronizer
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: lgtm, approved, dco-signoff: yes

#572 fix synchronizer to apply only appsub resources
  pkg/subscriber/namespace/secret_reconciler_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, dco-signoff: yes

#571 Enable external Kustomize plugins
  pkg/utils/kustomize.go
Labels: lgtm, approved, dco-signoff: yes

#573 Allow deny lists
  deploy/crds/apps.open-cluster-management.io_subscriptions_crd_v1.yaml
  pkg/apis/apps/ansible/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1/subscription_types.go
  pkg/apis/apps/v1/zz_generated.deepcopy.go
  pkg/controller/subscription/subscription_controller.go
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/subscriber/helmrepo/hemrepo_subscriber.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/subscriber/namespace/secret_reconciler_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/subscriber/processdeployable/deployable_queue.go
  pkg/synchronizer/kubernetes/sync_channel_test.go
  pkg/synchronizer/kubernetes/sync_client.go
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
Labels: lgtm, approved, dco-signoff: no

#577 fix policy deny
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes

#578 fix SSH known_hosts file create problem
  pkg/utils/gitrepo.go
Labels: approved, dco-signoff: yes

#576 Install the policy generator Kustomize plugin
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#579 appsub admin namespace scoped deployment
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/gitrepo_sync.go
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/subscriber/namespace/namespace_subscriber_suite_test.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved, dco-signoff: yes

#580 update hr version for sec vuln fix
  go.mod
  go.sum
  pkg/subscriber/namespace/deployable_subscriber_test.go
Labels: lgtm, approved, dco-signoff: yes

#582 allow appsub admin to deploy policies
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/git/git_subscriber.go
  pkg/synchronizer/kubernetes/synchronizer.go
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes

#583 fix comments
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes

#584 fix allow deny for object store subscription
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
Labels: approved, dco-signoff: yes

#585 for managed cluster subscription it should not have an owner reference
  pkg/controller/mcmhub/hub.go
Labels: lgtm, approved

#586 fix helmrelease configmap and secret refs
  common/config/.golangci.yml
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
Labels: lgtm, approved, dco-signoff: yes
