Repository stolostron/multicloud-operators-subscription, pull requests merged in 2021-12, with the labels that each got.

#606 Fix SSH key scan with port
  pkg/utils/gitrepo.go
Labels: lgtm, approved, dco-signoff: yes

#607 Use a better semver library to handle version parsing to deal with version that starts with a character v
  go.mod
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
Labels: lgtm, approved, dco-signoff: yes

#608 Update the Policy Generator to v1.2.3
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#610 Add a warning message when helm subscription fails to find a matching helm chart to deploy
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: lgtm, approved, dco-signoff: yes

#611 Git mtls
  docs/git_server_connection_types.md
  go.sum
  pkg/controller/mcmhub/hub_git.go
  pkg/subscriber/git/git_subscriber_item.go
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
Labels: approved, dco-signoff: yes

#612 upgrade to go v1.17
  .github/workflows/kind.yml
  build/Dockerfile.prow
  go.mod
Labels: approved, dco-signoff: yes

#613 Fix subscription spec changes not triggering Helm appsub updates
  pkg/controller/mcmhub/hook_test.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: lgtm, approved, dco-signoff: yes

#614 Test prow CICD
  README.md
Labels: lgtm, approved, dco-signoff: yes

#615 test prow CICD
  README.md
Labels: lgtm, approved, dco-signoff: yes

#616 test prow CICD
  README.md
Labels: lgtm, approved, dco-signoff: yes

#619 Don't watch placement decision api until it is installed
  cmd/manager/exec/manager.go
  cmd/placementrule/exec/manager.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/placementrule/utils/placement.go
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes

#620 skip updating the helmrelease kind resource to appsubstatus
  pkg/synchronizer/kubernetes/sync_appsubstatus.go
Labels: approved, dco-signoff: yes

#621 fix Git commit annotation change
  pkg/utils/subscription.go
Labels: approved, dco-signoff: yes

#623 Fix finalizer error when propagating subscriptions
  pkg/controller/mcmhub/hub.go
Labels: lgtm, approved, dco-signoff: no
