Repository stolostron/multicloud-operators-subscription, pull requests merged in 2021-08, with the labels that each got.

#538 change hub git watch interval to one hour
  pkg/controller/mcmhub/hub_git.go
Labels: approved, dco-signoff: yes

#537 update helmrelease version
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#539 change hub git watch interval to one hour
  pkg/controller/mcmhub/hub_git.go
Labels: lgtm, approved, dco-signoff: yes

#541 fix missing helm toplogy annotation when at least one resource in the chart fails to build
  go.mod
  go.sum
  pkg/controller/mcmhub/metaupdate.go
Labels: lgtm, approved, dco-signoff: yes

#543 add an event that bitbucket server sends
  pkg/webhook/listener/bitbucket_events.go
Labels: lgtm, approved, dco-signoff: yes

#545 Update patching_subscription_image.md
  docs/patching_subscription_image.md
Labels: approved, dco-signoff: no

#542 Upgrade k8s api to v0.21
  go.mod
  go.sum
  pkg/apis/apps/v1/v1_suite_test.go
  pkg/controller/mcmhub/gitrepo_sync_test.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hub_git.go
  pkg/controller/mcmhub/hub_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_suite_test.go
  pkg/controller/mcmhub/mcmhub_controller_test.go
  pkg/controller/mcmhub/metaupdate.go
  pkg/controller/mcmhub/metaupdate_test.go
  pkg/controller/spoketoken/spoke_toke_controller_test.go
  pkg/controller/spoketoken/spoke_token_controller.go
  pkg/controller/spoketoken/spoke_token_controller_suite_test.go
  pkg/controller/subscription/reference_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_suite_test.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/subscriber/git/git_subscriber_suite_test.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_suite_test.go
  pkg/subscriber/namespace/deployable_reconciler.go
  pkg/subscriber/namespace/deployable_subscriber_test.go
  pkg/subscriber/namespace/namespace_subscriber.go
  pkg/subscriber/namespace/namespace_subscriber_suite_test.go
  pkg/subscriber/namespace/secret_reconciler.go
  pkg/subscriber/namespace/secret_reconciler_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_suite_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_test.go
  pkg/synchronizer/kubernetes/cached_client.go
  pkg/synchronizer/kubernetes/sync_server.go
  pkg/synchronizer/kubernetes/sync_suite_test.go
  pkg/synchronizer/kubernetes/sync_test.go
  pkg/utils/deployable_test.go
  pkg/utils/gitrepo_test.go
  pkg/utils/helmrepo_test.go
  pkg/utils/kustomize.go
  pkg/utils/subscription_test.go
  pkg/utils/util_suite_test.go
  pkg/webhook/listener/bitbucket_events_test.go
  pkg/webhook/listener/gitlab_events_test.go
  pkg/webhook/listener/webhook_listener_suite_test.go
  pkg/webhook/listener/webhook_listener_test.go
  pkg/webhook/listener/webhook_listner.go
Labels: approved, dco-signoff: yes

#546 upgrade subscription release
  go.mod
  go.sum
  pkg/webhook/listener/bitbucket_events.go
Labels: lgtm, approved, dco-signoff: yes

#550 fix webhook
  pkg/subscriber/git/git_subscriber.go
Labels: approved, dco-signoff: yes

#552 appsub controller failed to start after k8s api upgrade
  cmd/manager/exec/manager.go
  pkg/subscriber/namespace/namespace_subscriber.go
Labels: approved, dco-signoff: yes

#553 fix webhook
  pkg/subscriber/git/git_subscriber.go
Labels: approved, dco-signoff: yes

#555 fix kubebuilder url
  README.md
  build/setup-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#560 fix secondary channel for helm and objectbucket hub
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/helmrepo/helm_subscriber_item.go
Labels: approved, dco-signoff: yes

#562 add helmrelease tests metadata files
  testhr/github/nginx-chart-upgrade/nginx-chart/Chart.yaml
  testhr/github/nginx-chart-upgrade/nginx-chart/templates/NOTES.txt
  testhr/github/nginx-chart-upgrade/nginx-chart/templates/_helpers.tpl
  testhr/github/nginx-chart-upgrade/nginx-chart/templates/deployment.yaml
  testhr/github/nginx-chart-upgrade/nginx-chart/templates/service.yaml
  testhr/github/nginx-chart-upgrade/nginx-chart/values.yaml
  testhr/github/nginx-chart/Chart.yaml
  testhr/github/nginx-chart/templates/NOTES.txt
  testhr/github/nginx-chart/templates/_helpers.tpl
  testhr/github/nginx-chart/templates/deployment.yaml
  testhr/github/nginx-chart/templates/service.yaml
  testhr/github/nginx-chart/values.yaml
  testhr/github/subscription-release-test-1/.helmignore
  testhr/github/subscription-release-test-1/Chart.yaml
  testhr/github/subscription-release-test-1/templates/_helpers.tpl
  testhr/github/subscription-release-test-1/templates/deployment_subscription_release.yaml
  testhr/github/subscription-release-test-1/values.yaml
  testhr/github/subscription-release-test-2/.helmignore
  testhr/github/subscription-release-test-2/Chart.yaml
  testhr/github/subscription-release-test-2/templates/_helpers.tpl
  testhr/github/subscription-release-test-2/templates/deployment_subscription_release.yaml
  testhr/github/subscription-release-test-2/values.yaml
  testhr/github/subscription-release-test-3/.helmignore
  testhr/github/subscription-release-test-3/Chart.yaml
  testhr/github/subscription-release-test-3/templates/_helpers.tpl
  testhr/github/subscription-release-test-3/templates/deployment_subscription_release.yaml
  testhr/github/subscription-release-test-3/values.yaml
  testhr/helmrepo/index.yaml
  testhr/helmrepo/nginx-chart-0.1.0.tgz
  testhr/helmrepo/nginx-chart-0.2.0.tgz
  testhr/helmrepo/nginx-ingress-1.40.0_keep.tgz
  testhr/helmrepo/subscription-release-test-1-0.1.0.tgz
  testhr/helmrepo/subscription-release-test-3-0.1.0.tgz
Labels: approved, dco-signoff: yes
