Repository stolostron/multicloud-operators-subscription, pull requests merged in 2022-05, with the labels that each got.

#727 typo fix
  pkg/controller/mcmhub/hub.go
Labels: lgtm, approved, dco-signoff: yes

#729 always update token secret on reconcile
  pkg/controller/spoketoken/spoke_token_controller.go
Labels: lgtm, approved, dco-signoff: yes

#728 always update token secret on reconcile
  pkg/controller/spoketoken/spoke_token_controller.go
Labels: approved, dco-signoff: yes

#731 Update the Policy Generator version to v1.7.0
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#732 Use git-core package instead of git in Docker image
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes

#733 Use git-core package instead of git in Docker image
  build/Dockerfile
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes

#734 Use git-core package instead of git in Docker image
  build/Dockerfile
  build/run-e2e-tests.sh
Labels: approved, dco-signoff: yes

#735 Fix Git subscription for Helm charts not deleting older HelmRelease
  build/e2e-kc.sh
  pkg/synchronizer/kubernetes/sync_appsubstatus.go
  test/e2e/cases/15-git-helm/install/channel.yaml
  test/e2e/cases/15-git-helm/install/placement.yaml
  test/e2e/cases/15-git-helm/install/subscription.yaml
  test/e2e/cases/15-git-helm/update/subscription.yaml
Labels: lgtm, approved, dco-signoff: yes

#730 Adding the Updated column for Subscription
  addon/manifests/chart/templates/apps.open-cluster-management.io_subscriptions_crd_v1.yaml
  deploy/crds/apps.open-cluster-management.io_subscriptions_crd_v1.yaml
  pkg/apis/apps/v1/subscription_types.go
Labels: lgtm, approved, needs-ok-to-test, ok-to-test, dco-signoff: yes

#736 no op
  docs/development.md
Labels: dco-signoff: yes

#737 toggle cicd build
  README.md
Labels: approved, dco-signoff: yes

#738 Always update cluster appsubreport
  pkg/synchronizer/kubernetes/sync_appsubstatus.go
Labels: lgtm, approved, dco-signoff: yes

#739 don't evaluate user managed clusters permission by creating SelfSubje…
  pkg/placementrule/controller/placementrule/placement.go
Labels: lgtm, approved, dco-signoff: yes

#740 fix typo in addon CRD
  addon/manifests/chart/templates/apps.open-cluster-management.io_subscriptions_crd_v1.yaml
Labels: approved, dco-signoff: yes

#743 add current namespace scoped feature back
  pkg/apis/apps/v1/subscription_types.go
  pkg/controller/mcmhub/propagate_manifestwork.go
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/git/git_subscriber_item.go
Labels: lgtm, approved, dco-signoff: yes

#742 Ignore package delete error if it is deleted already
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: lgtm, approved, dco-signoff: yes

#744 fix allow, deny, secondary channel
  pkg/controller/mcmhub/propagate_manifestwork.go
Labels: approved, dco-signoff: yes

#745 release-2.4 only - set default value for helmrelease chart directory
  go.mod
  go.sum
  pkg/controller/mcmhub/metaupdate.go
Labels: lgtm, approved, dco-signoff: yes

#746 validate managed cluster get role via checking all multiple cluster r…
  pkg/placementrule/controller/placementrule/placement.go
Labels: lgtm, approved, dco-signoff: yes

#747 Add a new line to sonar config file
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes
