Repository stolostron/multicloud-operators-subscription, pull requests merged in 2023-10, with the labels that each got.

#1017 fix e2e tests
  build/run-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#1018 Ensure all containers run with r/o root fs and other std securityCont…
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes

#1019 stop synchronizing resources list if any kustomization folder fails
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes, do-not-merge/hold

#1021 stop synchronizing resources list if any kustomization folder fails (…
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes

#1022 stop synchronizing resources list if any kustomization folder fails -…
  pkg/subscriber/git/git_subscriber_item.go
Labels: approved, dco-signoff: yes
