Repository stolostron/multicloud-operators-subscription, pull requests merged in 2023-06, with the labels that each got.

#977 [release-2.7] Use `release-2.7` for the generator
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#978 [release-2.6] Use `release-2.6` for the generator
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#979 Update generator to `release-2.9`
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#981 Update gitopsclusters CRD
  deploy/olm-catalog/multicluster-operators-subscription/manifests/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml
Labels: lgtm, approved, dco-signoff: yes

#983 Increase mem limit for gitopscluster controller
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#984 avoid delete appsub addon CRDs when the regional hub is detached (#34…
  addon/addon.go
  addon/manifests/chart/templates/apps.open-cluster-management.io_helmreleases_crd.yaml
  addon/manifests/chart/templates/apps.open-cluster-management.io_subscriptions_crd_v1.yaml
  addon/manifests/chart/templates/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml
  addon/manifests/chart/values.yaml
Labels: approved, dco-signoff: yes, do-not-merge/hold

#985 avoid delete appsub addon CRDs when the regional hub is detached (#34…
  addon/addon.go
  addon/manifests/chart/templates/apps.open-cluster-management.io_helmreleases_crd.yaml
  addon/manifests/chart/templates/apps.open-cluster-management.io_subscriptions_crd_v1.yaml
  addon/manifests/chart/templates/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml
  addon/manifests/chart/values.yaml
Labels: approved, dco-signoff: yes
