Repository stolostron/multicloud-operators-subscription, pull requests merged in 2025-09, with the labels that each got.

#1374 feat: adding argocd-agent to gitops addon requires the following install related manifests changes
  deploy/olm-catalog/multicluster-operators-subscription/manifests/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml
  deploy/olm-catalog/multicluster-operators-subscription/manifests/gitops-addon.addonTemplates.yaml
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#1377 move to konflux common pipeline
  .tekton/multicluster-operators-subscription-acm-214-pull-request.yaml
  .tekton/multicluster-operators-subscription-acm-214-push.yaml
Labels: approved, dco-signoff: yes

#1378 Support Kustomization for AppSub ObjectBucket Channel
  Makefile
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_objectbucket_kustomize_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_propagation_test.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/subscriber/objectbucket/objectbucket_kustomize_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/utils/fake_s3_server.go
  pkg/utils/kustomize.go
  pkg/utils/kustomize_s3_test.go
Labels: approved, dco-signoff: yes

#1379 chore(KONFLUX-6210): fix and set name and cpe label for multicluster-operators-subscription-acm-214
  build/Dockerfile.rhtap
Labels: ok-to-test, dco-signoff: yes

#1380 fix and set name and cpe label
  build/Dockerfile.rhtap
Labels: lgtm, approved, dco-signoff: yes, do-not-merge/hold

#1381 installer update for gitopscluster changes
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes

#1383 chore: installer update with new gitopscluster API change
  deploy/olm-catalog/multicluster-operators-subscription/manifests/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml
Labels: approved, dco-signoff: yes

#1385 chore: installer updates for GitOpsCluster API changes
  deploy/olm-catalog/multicluster-operators-subscription/manifests/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml
  deploy/olm-catalog/multicluster-operators-subscription/manifests/gitops-addon.addonTemplates.yaml
Labels: lgtm, approved, dco-signoff: yes

#1386 Support Kustomization for AppSub ObjectBucket Channel (#1378)
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/hub_objectbucket_kustomize_test.go
  pkg/controller/mcmhub/mcmhub_controller.go
  pkg/controller/mcmhub/mcmhub_controller_propagation_test.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/subscriber/objectbucket/objectbucket_kustomize_test.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/utils/fake_s3_server.go
  pkg/utils/kustomize.go
  pkg/utils/kustomize_s3_test.go
Labels: lgtm, approved, dco-signoff: yes
